void wr_ecltxt(std::ostream&os,const std::vector<LunarEclipse>&items,int tz_off){
	os<<"type\tpen_mag\tumb_mag\tgamma\teps_deg\tdt_max_sec\tdur_pen_sec\t"
		 "dur_umb_sec\tdur_tot_sec\trp_re\tru_re\topp_rp_re\topp_ru_re\t"
		 "moon_dist_km\tsun_ra_deg\tsun_dec_deg\tsun_sd_deg\tsun_ehp_deg\t"
		 "moon_ra_deg\tmoon_dec_deg\tmoon_sd_deg\tmoon_ehp_deg\tlib_l_deg\t"
		 "lib_b_deg\tlib_c_deg\topp_liso\tmax_liso\tp1_liso\tu1_liso\tu2_liso\t"
		 "u3_liso\tu4_liso\tp4_liso\t"
		 "p1_jd_ut1\tp1_jd_td\tp1_jd\tp1_zen_lat_deg\tp1_zen_lon_deg\t"
		 "p1_pa_deg\tp1_axis_deg\tu1_jd_ut1\tu1_jd_td\tu1_jd\tu1_zen_lat_deg\t"
		 "u1_zen_lon_deg\tu1_pa_deg\tu1_axis_deg\tu2_jd_ut1\tu2_jd_td\tu2_jd\t"
		 "u2_zen_lat_deg\tu2_zen_lon_deg\tu2_pa_deg\tu2_axis_deg\t"
		 "opp_jd_ut1\topp_jd_td\topp_jd\topp_zen_lat_deg\topp_zen_lon_deg\t"
		 "opp_pa_deg\topp_axis_deg\t"
		 "max_jd_ut1\tmax_jd_td\tmax_jd\tmax_zen_lat_deg\tmax_zen_lon_deg\t"
		 "max_pa_deg\tmax_axis_deg\tu3_jd_ut1\tu3_jd_td\tu3_jd\tu3_zen_lat_deg\t"
		 "u3_zen_lon_deg\tu3_pa_deg\tu3_axis_deg\tu4_jd_ut1\tu4_jd_td\tu4_jd\t"
		 "u4_zen_lat_deg\tu4_zen_lon_deg\tu4_pa_deg\tu4_axis_deg\t"
		 "p4_jd_ut1\tp4_jd_td\tp4_jd\tp4_zen_lat_deg\tp4_zen_lon_deg\t"
		 "p4_pa_deg\tp4_axis_deg\n";
	os<<std::setprecision(17);
	for(const auto&ecl : items){
		os<<ecl.type<<"\t";
		wr_num_txt(os,ecl.pen_mag);
		os<<"\t";
		wr_num_txt(os,ecl.umb_mag);
		os<<"\t";
		wr_num_txt(os,ecl.gamma);
		os<<"\t";
		wr_num_txt(os,ecl.eps_deg);
		os<<"\t";
		wr_num_txt(os,ecl.dt_max_sec);
		os<<"\t";
		wr_num_txt(os,ecl.dur_pen_sec);
		os<<"\t";
		wr_num_txt(os,ecl.dur_umb_sec);
		os<<"\t";
		wr_num_txt(os,ecl.dur_tot_sec);
		os<<"\t";
		wr_num_txt(os,ecl.rp_re);
		os<<"\t";
		wr_num_txt(os,ecl.ru_re);
		os<<"\t";
		wr_num_txt(os,ecl.opp_rp_re);
		os<<"\t";
		wr_num_txt(os,ecl.opp_ru_re);
		os<<"\t";
		wr_num_txt(os,ecl.moon_dist_km);
		os<<"\t";
		wr_num_txt(os,ecl.sun_geo.ra_deg);
		os<<"\t";
		wr_num_txt(os,ecl.sun_geo.dec_deg);
		os<<"\t";
		wr_num_txt(os,ecl.sun_geo.sd_deg);
		os<<"\t";
		wr_num_txt(os,ecl.sun_geo.ehp_deg);
		os<<"\t";
		wr_num_txt(os,ecl.moon_geo.ra_deg);
		os<<"\t";
		wr_num_txt(os,ecl.moon_geo.dec_deg);
		os<<"\t";
		wr_num_txt(os,ecl.moon_geo.sd_deg);
		os<<"\t";
		wr_num_txt(os,ecl.moon_geo.ehp_deg);
		os<<"\t";
		wr_num_txt(os,ecl.lib.l_deg);
		os<<"\t";
		wr_num_txt(os,ecl.lib.b_deg);
		os<<"\t";
		wr_num_txt(os,ecl.lib.c_deg);
		os<<"\t"<<node_liso(ecl.jd_tdb_opp,tz_off)
		  <<"\t"<<node_liso(ecl.jd_tdb_max,tz_off)
		  <<"\t"<<node_liso(ecl.jd_tdb_p1,tz_off)
		  <<"\t"<<node_liso(ecl.jd_tdb_u1,tz_off)
		  <<"\t"<<node_liso(ecl.jd_tdb_u2,tz_off)
		  <<"\t"<<node_liso(ecl.jd_tdb_u3,tz_off)
		  <<"\t"<<node_liso(ecl.jd_tdb_u4,tz_off)
		  <<"\t"<<node_liso(ecl.jd_tdb_p4,tz_off)
		  <<"\t";
		wr_node_txt(os,ecl.jd_tdb_p1,ecl.p1_meta);
		os<<"\t";
		wr_node_txt(os,ecl.jd_tdb_u1,ecl.u1_meta);
		os<<"\t";
		wr_node_txt(os,ecl.jd_tdb_u2,ecl.u2_meta);
		os<<"\t";
		wr_node_txt(os,ecl.jd_tdb_opp,ecl.opp_meta);
		os<<"\t";
		wr_node_txt(os,ecl.jd_tdb_max,ecl.max_meta);
		os<<"\t";
		wr_node_txt(os,ecl.jd_tdb_u3,ecl.u3_meta);
		os<<"\t";
		wr_node_txt(os,ecl.jd_tdb_u4,ecl.u4_meta);
		os<<"\t";
		wr_node_txt(os,ecl.jd_tdb_p4,ecl.p4_meta);
		os<<"\n";
	}
}

